#!/bin/sh
if [ $# -eq 0 ] || [ $# -ge 2 ]
then
    echo "[Usage]: . goto <destination>"
    exit
fi

case $1 in
    dltb)
        cd /home/jiangliang/code/DeepLearnToolbox
        ;;
    sc)
        cd /home/jiangliang/code/semantic-colorization
        ;;
    flickr8)
        cd /home/jiangliang/datasets/flickr8k
        ;;
    scripts)
        cd /home/jiangliang/code/scripts
        ;;
    ck)
        cd /home/jiangliang/code/colorization-keras
        ;;
    ck1)
        cd /home/jiangliang/code/colorization-keras-1
        ;;
    pylib)
        cd /home/jiangliang/software/python2.7.5/lib/python2.7/site-packages
        ;;
    *)
        echo "Wrong destination"
        ;;
esac
