#!/bin/sh
if [ $# -eq 0 ] || [ $# -ge 2 ]
then
    echo "[Usage]: . goto <destination>"
    exit
fi

case $1 in
    # add destinations by yourself
    cc)
        cd /home/liangjiang/code/caffe_colorization
        ;;
    c)
        cd /home/liangjiang/code/caffe
        ;;
    rn)
        cd /home/liangjiang/code/residual_network
        ;;
    drn)
        cd /home/liangjiang/code/deep-residual-networks
        ;;
    old)
        ssh jiangliang@172.16.46.3
        ;;
    *)
        echo "Wrong destination"
        ;;
esac
