#!/bin/sh
if [ $# -eq 0 ] || [ $# -ge 2 ]
then
    echo "[Usage]: . goto <destination>"
    exit
fi

case $1 in
    # add destinations by yourself
    *)
        echo "Wrong destination"
        ;;
esac
