#!/bin/sh
if [ $# -eq 0 ] || [ $# -gt 1 ]
then
    echo "[Usage]: switchkey <key_name>"
    exit
fi

echo "starting ssh-agent..."
eval `ssh-agent -s`

case $1 in
    mygithub)
        key="/home/liangjiang/.ssh/mygithub"
        ;;
    coding.net)
        key="/home/liangjiang/.ssh/coding.net"
        ;;
    *)
        echo "Wrong key"
        ;;
esac
ssh-add -D
ssh-add $key
ssh-add -l

