#!/bin/sh
if [ $# -eq 0 ] || [ $# -gt 1 ]
then
    echo "[Usage]: switchkey <key_name>"
    exit
fi

echo "starting ssh-agent..."
eval `ssh-agent -s`

key="/home/liangjiang/.ssh/"$1
ssh-add -D
ssh-add $key
ssh-add -l

